model:
  base_learning_rate: 4.0e-06
  target: src.model_mesh.MVRecon
  params:
    mesh_save_root: Objaverse
    init_ckpt: nerf_base.ckpt
    input_size: 512
    render_size: 512
    use_tv_loss: true
    sample_points: null
    use_gt_albedo: false
    
    lrm_generator_config:
      target: src.models.lrm_mesh.PRM
      params:
        encoder_feat_dim: 768
        encoder_freeze: false
        encoder_model_name: facebook/dino-vitb16
        transformer_dim: 1024
        transformer_layers: 16
        transformer_heads: 16
        triplane_low_res: 32
        triplane_high_res: 64
        triplane_dim: 80
        rendering_samples_per_ray: 128
        grid_res: 128
        grid_scale: 2.1


data:
  target: src.data.objaverse.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    train:
      target: src.data.objaverse.ObjaverseData
      params:
        root_dir: Objaverse
        light_dir: env_mipmap
        input_view_num: [6]
        target_view_num: 6
        total_view_n: 18
        distance: 5.0
        fov: 30
        camera_random: true
        validation: false
    validation:
      target: src.data.objaverse.ValidationData
      params:
        root_dir: Objaverse
        input_view_num: 6
        input_image_size: 320
        fov: 30


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 100
      save_top_k: -1
      save_last: true
  callbacks: {}

  trainer:
    benchmark: true
    max_epochs: -1
    val_check_interval: 2000000000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 8
    log_every_n_steps: 1
    check_val_every_n_epoch: null   # if not set this, validation does not run
